{% set name = "ford" %}
{% set version = "6.1.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Fortran-FOSS-Programmers/ford/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 76055da4d947802e9c664509a0af4ebc339ae48d9acdd00894299bb8db9141cc

build:
  number: 0
  entry_points:
    - {{ name }} = {{ name }}:run
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - beautifulsoup4 >=4.5.1
    - python-graphviz >=0.20.0
    - jinja2 >=2.1
    - markdown >=3.4.0
    - markdown-include >=0.7.0
    - pygments >=2.12.0,<2.13.0
    - python >=3.8
    - python-markdown-math >=0.8
    - toposort >=1.7.0
    - tqdm >=4.64.0

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - {{ name }} --help
  requires:
    - pip

about:
  home: https://github.com/Fortran-FOSS-Programmers/ford
  summary: FORD, standing for FORtran Documenter, is an automatic documentation generator for modern Fortran programs.
  dev_url: https://github.com/Fortran-FOSS-Programmers/ford
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
