{% set name = "ford" %}
{% set version = "6.1.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Fortran-FOSS-Programmers/ford/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9508d1ea6818679ca2255224d013dd7153a8e03dba9caffde7e1dec97e0254b1

build:
  number: 0
  entry_points:
    - {{ name }} = {{ name }}:run
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - beautifulsoup4 >=4.5.1
    - python-graphviz
    - jinja2 >=2.1
    - markdown
    - markdown-include >=0.5.1
    - pygments
    - python >=3.8
    - python-markdown-math >=0.8
    - toposort
    - tqdm

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - {{ name }} --help
  requires:
    - pip

about:
  home: https://github.com/Fortran-FOSS-Programmers/ford
  summary: FORD, standing for FORtran Documenter, is an automatic documentation generator for modern Fortran programs.
  dev_url: https://github.com/Fortran-FOSS-Programmers/ford
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
